<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Comeval')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>


        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css?c=4'))
                ->prependStylesheet($this->basePath('css/login.css?c=2'))
        ?>
        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <!-- <div class="container"> -->
        <div class="">
            <?php if ($this->flashMessenger()->hasMessages()): ?>
                <div class="alert alert-info flash-messenger">
                    <?= $this->flashMessenger()->setAutoEscape(false)->render(); ?>
                </div>
            <?php endif; ?>

            <?php
            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat('<div %s>')
                    ->setMessageCloseString('<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button></div>');
            echo $flash->renderCurrent('error', array('alert', 'alert-dismissible fade show', 'alert-danger'));
            echo $flash->renderCurrent('info', array('alert', 'alert-dismissible fade show', 'alert-info'));
            echo $flash->renderCurrent('default', array('alert', 'alert-dismissible', 'alert-warning'));
            echo $flash->renderCurrent('success', array('alert', 'alert-success', 'alert-dismissible fade show'));
            ?>

            <?= $this->content ?>
            <footer>
                <p class="tex-center">&copy; <?= date('Y') ?></p>
            </footer>
        </div>
        <div id="load-vfx"></div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script>
            $(document).ready(() => {
                setTimeout(() => {
                    $('#load-vfx').fadeOut('slow');
                }, 500);
            });
        </script>
    </body>
</html>
