<div class="modal fade" id="modalSolicitudes" tabindex="-1" aria-labelledby="modalSolicitudes" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Rechazar solicitud</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="closeModalAdm()">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" title="rechazar">
                <form method="POST">
                    <div class="mb-3">
                        <label for="" class="form-label">Motivo del rechazo de la solicitud</label>
                        <textarea class="form-control" rows="3" name="mensaje"></textarea>
                        <input type='hidden' name='action' value='rechazar' />
                        <input type='hidden' name='id_usuario' value="<?= $this->solicitudData[0]["id_usuario"]; ?>" />
                    </div>

                    <div class="mt-3">
                        <input type="submit" class="btn btn-primary" value="Enviar" /> 
                    </div>
                </form>

            </div>
        
        </div>
    </div>
</div>


<div class="row">

    <div class="">

        <div class="row">
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-4 shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-principal text-uppercase mb-1">
                                    Puntos Solicitud</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800" id="label_pts"> 0 </div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="card flex-fill">

            <div class="card-header">
                <h5 class="card-title mb-0"> Cargos desempeñados </h5>
            </div>

            <div class="card-body" >

                <form class="user needs-validation" method="POST" enctype="multipart/form-data">
                    
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label class="form-label" for="tipo_cargo">Tipo de cargo desempeñado</label>
                            <select class="form-select form-control" name="tipo_cargo" id="tipo_cargo" onchange="validateTipoCargo(this)" required disabled>
                                <option selected disabled value="">Seleccione el tipo de cargo desempeñado</option>
                                <option value="3.1">Cargos desempeñados por elección en la USAC</option>
                                <option value="3.2">Cargos desempeñados por nombramiento en la USAC</option>
                                <option value="3.3">Cargos desempeñados por elección fuera de USAC</option>
                                <option value="3.4">Cargos desempeñados por nombramientos fuera de la USAC</option>
                            </select>
                            <div class="invalid-feedback">
                                Por favor seleccione el cargo desempeñado
                            </div>
                            <!-- <input type="text" class="form-control form-control-user" id="institution" name="institucion"
                                placeholder="Institución o unidad académica"> -->
                        </div>
                        <div class="col-sm-6" id="div_nombramiento">
                            <label class="form-label" for="tipo_nombramiento">Cargo desempeñado</label>
                            <select class="form-select form-control" name="tipo_nombramiento" id="tipo_nombramiento" onchange="validateTipoCargoEleccion(this)" disabled>
                                <option selected>Seleccione el tipo de cargo desempeñado</option>
                            </select>
                        </div>

                    </div>
                    

                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label id="label_institucion" class="form-label" for="institucion">Unidad Académica / Institución</label>
                            <input type="text" class="form-control form-control-user" id="institucion" name="institucion" value="<?= $this->solicitudData[0]["institucion"]; ?>"
                                placeholder="Ingrese el nombre de la  Unidad Académica/Institución" required disabled> 
                            <div class="invalid-feedback">
                                Por favor escriba el nombre de la institución
                            </div>

                        </div>
                        <div class="col-sm-6">
                            <label class="form-label" for="institucion">Nombre del cargo</label>
                            <input type="text" class="form-control form-control-user" id="nombre_cargo" name="nombre_cargo" value="<?= $this->solicitudData[0]["nombre_cargo"]; ?>"
                                placeholder="Nombre del cargo" required disabled> 
                            <div class="invalid-feedback">
                                Por favor escriba el nombre de la institución
                            </div>

                        </div>
                    </div>

                    
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label for="fecha_obtencion">Duración: (Meses)</label>
                            <input type="number" class="form-control form-control-user" id="duracion_en_cargo" name="duracion_en_cargo" value="<?= $this->solicitudData[0]["duracion_en_cargo"]; ?>"
                            placeholder="Escriba el año de obtención" required disabled>
                            <div class="invalid-feedback">
                                Por favor escriba el nombre de la institución
                            </div>

                        </div>

                        <div class="col-sm-6">
                            <label for="">Constancia</label>
                            <br>
                            <a class="btn btn-primary" href="<?= $this->url("meritosHome/meritos", ["action" => "displayfile" , "val1"=> $this->solicitudData[0]['url_constancia']]) ?>" target="_blank">
                                Constancia
                            </a>
                            <!-- <input type="file" class="form-control"
                                id="archivo" name="subir_archivo" required>
                            <div class="invalid-feedback">
                                Por favor suba la constancia del cargo desempeñado
                            </div> -->

                        </div>

                    </div>

                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <input type="hidden" class="form-control" value="1"
                                id="id_estado" name="id_estado">
                        </div>

                        <div class="col-sm-6">
                            <input type="hidden" class="form-control" value="<?= $this->solicitudData[0]["id_usuario"]; ?>"
                                id="id_usuario" name="id_usuario">
                        </div>

                        <div class="col-sm-6">
                            <input type="hidden" class="form-control" value="0"
                                id="puntos" name="puntos">
                        </div>
                        <input type='hidden' name='action' value='aceptar' />

                    </div>

                
                    <div class="container">
                        <div class="row">
                            <div class="col-sm">
                                <div class="mt-3">
                                    <input type="submit" class="btn btn-primary" value="Aceptar" /> 
                                </div>
                            </div>
                            <div class="col-sm">
                                <div class="mt-3">
                                    <a class="btn btn-danger" onclick="openModalAdm();">
                                        Rechazar
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </form>


            </div>
    
        </div>

    </div>

</div>


<script>

let listaCargos = [
  {
    type: "3.1",
    value: "3.1.1",
    name: "1 cargo o más",
    puntos: 4,
  },
  {
    type: "3.2",
    value: "3.2.1",
    name: "Dirección y Programa Interciclos",
    puntos: 4,
  },
  {
    type: "3.2",
    value: "3.2.2",
    name: "Coordinador de nivel, área o departamento",
    puntos: 3,
  },
  {
    type: "3.2",
    value: "3.2.3",
    name: "Coordinador de curso",
    puntos: 1,
  },
  {
    type: "3.2",
    value: "3.2.4",
    name: "Otros nombramientos",
    puntos: 1,
  },
  {
    type: "3.3",
    value: "3.3.1",
    name: "2 cargos o más",
    puntos: 4,
  },
  {
    type: "3.3",
    value: "3.3.2",
    name: "1 cargo",
    puntos: 2,
  },
  {
    type: "3.4",
    value: "3.4.1",
    name: "Por cada cargo",
    puntos: 1,
  },
];

function cargarInfoTipoCargo(value) {
    let categorias = listaCargos.filter((e) => e.type == value);
    const select = document.getElementById("tipo_nombramiento");
    //clearSelect(select);
    for (const option of categorias) {
        let newOption = document.createElement("option");
        newOption.value = option.value;
        newOption.text = option.name;
        select.add(newOption);
    }
    select.selectedIndex = 0;
    document.querySelector("#label_pts").innerHTML = "0";
    document.querySelector("#puntos").value = 0;
}

function cargarInfo(data) {
    //console.log(data);
    document.getElementById("tipo_cargo").value = data.tipo_cargo;
    cargarInfoTipoCargo(data.tipo_cargo);

    document.getElementById("tipo_nombramiento").value = data.tipo_nombramiento;
    let valueObject = listaCargos.find((e) => e.value == data.tipo_nombramiento);
    document.querySelector("#label_pts").innerHTML = valueObject.puntos;
    document.querySelector("#puntos").value = valueObject.puntos;
    

}

cargarInfo(<?= json_encode($this->solicitudData[0]) ?>);

</script>