<div class="modal fade" id="modalSolicitudes" tabindex="-1" aria-labelledby="modalSolicitudes" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Rechazar solicitud</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="closeModalAdm()">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST">
                    <div class="mb-3">
                        <label for="" class="form-label">Motivo del rechazo de la solicitud</label>
                        <textarea class="form-control" id="mensaje" name="mensaje" rows="3"></textarea>
                        <input type='hidden' name='action' value='rechazar' />
                        <input type='hidden' name='id_usuario' value="<?= $this->solicitudData[0]["id_usuario"]; ?>" />
                    
                    </div>

                    <div class="mt-3">
                        <input type="submit" class="btn btn-primary" value="Enviar" /> 
                    </div>
                </form>

            </div>
        
        </div>
    </div>
</div>


<div class="row">

    <div class="">

        <div class="row">
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-3 shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-principal text-uppercase mb-1">
                                    Puntos Solicitud</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800" id="label_pts"> 0 </div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="card flex-fill">

            <div class="card-header">
                <h5 class="card-title mb-0"> Formación profesional </h5>
            </div>

            <div class="card-body">

                <form class="user needs-validation" method="POST" enctype="multipart/form-data" novalidate>
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label class="form-label" for="institucion">Institución otorgante</label>
                            <input type="text" class="form-control form-control-user" id="institution" name="institucion" value="<?= $this->solicitudData[0]["institucion"]; ?>"
                                placeholder="Institución otorgante" disabled required>
                            <div class="invalid-feedback">
                                Por favor escriba el nombre de la institución
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label for="">Nivel de titulo obtenido</label>
                            <select class="form-select form-control" aria-label="Default select example" name="nivel_titulo" id="nivel_titulo" onchange="validateFormacion(this)" required disabled>
                                <option selected disabled value="">Seleccione el nivel del titulo obtenido</option>
                                <option value="doctorado">Estudios de Doctorado</option>
                                <option value="maestria">Estudios de Maestria</option>
                                <option value="licenciatura">Estudios a nivel de Licenciatura</option>
                                <option value="nivel_intermedio">Estudios universitarios a nivel intermedio</option>
                            </select>
                            <div class="invalid-feedback">
                                Por favor escriba el nivel del titulo obtenido
                            </div>
                        </div>
                    </div>
                    

                    
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label for="">Seleccione la categoria</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="categoria" value="graduado" id="graduado"  onchange="validateCategoria(this)" required disabled>
                                <label class="form-check-label" for="graduado">
                                    Graduado
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="categoria" value="pensum" id="pensum" onchange="validateCategoria(this)" required disabled>
                                <label class="form-check-label" for="pensum">
                                    Cierre de pensum
                                </label>
                                <div class="invalid-feedback">
                                    Por favor seleccione una categoria
                                </div>
                            </div>

                        </div>

                        <div class="col-sm-6">
                            <label for="fecha_obtencion" id="label_year">Año de graduación o cierre de pensum</label>
                            <input type="number" class="form-control form-control-user" id="fecha_obtencion" name="fecha_obtencion"
                                placeholder="Escriba el año de obtención" required disabled>
                            <div class="invalid-feedback">
                                Por favor escriba el año de graduación/cierre de pensum
                            </div>
                        </div>

                    </div>

                    <div class="form-group row">
                    
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label for="titulo">Titulo</label>
                            <input type="text" class="form-control form-control-user" id="titulo" name="titulo" value="<?= $this->solicitudData[0]["titulo"]; ?>"
                                placeholder="Escriba el nombre del titulo obtenido" disabled required>
                            <div class="invalid-feedback">
                                Por favor escriba el nombre del titulo
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label for="">Constancia del titulo obtenido</label>
                            <br>
                            <a class="btn btn-primary" href="<?= $this->url("meritosHome/meritos", ["action" => "displayfile" , "val1"=> $this->solicitudData[0]['url_constancia']]) ?>" target="_blank">
                                Constancia
                            </a>
                            
                            <!-- <input type="file" class="form-control" onchange="validateFile(this)"
                                id="archivo" name="subir_archivo" required>
                            <div class="invalid-feedback">
                                Por favor suba la constancia de su titulo obtenido
                            </div> -->
                        </div>
                        
                    </div>

                    <!-- <input type="hidden" class="form-control form-control-user" id="puntos" name="puntos"> -->
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <input type="hidden" class="form-control" value="1"
                                id="id_estado" name="id_estado" required>
                        </div>

                        <div class="col-sm-6">
                            <input type="hidden" class="form-control" value="<?= $this->solicitudData[0]["id_usuario"]; ?>"
                                id="id_usuario" name="id_usuario">
                        </div>

                        <div class="col-sm-6">
                            <input type="hidden" class="form-control" id="puntos" name="puntos">
                        </div>

                        <input type='hidden' name='action' value='aceptar' />

                    </div>

                    <div class="container">
                        <div class="row">
                            <div class="col-sm">
                                <div class="mt-3">
                                    <input type="submit" class="btn btn-primary" value="Aceptar" /> 
                                </div>
                            </div>
                            <div class="col-sm">
                                <div class="mt-3">
                                    <a class="btn btn-danger" onclick="openModalAdm();">
                                        Rechazar
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </form>



            </div>
    
        </div>

    </div>

</div>


<script>

let optionsFormacion = [
    {
        categoria: 'graduado',
        nivel_titulo: 'doctorado',
        puntos: 10
    },
    {
        categoria: 'graduado',
        nivel_titulo: 'maestria',
        puntos: 8.5
    },
    {
        categoria: 'graduado',
        nivel_titulo: 'licenciatura',
        puntos: 7
    },
    {
        categoria: 'graduado',
        nivel_titulo: 'nivel_intermedio',
        puntos: 5
    },
    {
        categoria: 'pensum',
        nivel_titulo: 'doctorado',
        puntos: 9
    },
    {
        categoria: 'pensum',
        nivel_titulo: 'maestria',
        puntos: 8
    },
    {
        categoria: 'pensum',
        nivel_titulo: 'licenciatura',
        puntos: 6
    }
]

function cargarInfo(data) {
    //console.log(data);
    document.getElementById("nivel_titulo").value = data.nivel_titulo;
    let categoria = (data.anio_graduacion) ? 'graduado' : 'pensum';
    
    if(categoria == 'graduado'){
        document.getElementById(`graduado`).checked = true;    
        document.getElementById(`fecha_obtencion`).value = data.anio_graduacion;    
        
    }else if(categoria == 'pensum'){
        document.getElementById(`pensum`).checked = true; 
        document.getElementById(`fecha_obtencion`).value = data.anio_cierre_pensum;    
    }

    let valueObject = optionsFormacion.find((e) => e.nivel_titulo == data.nivel_titulo && e.categoria == categoria);
    document.querySelector("#label_pts").innerHTML = valueObject.puntos;
    document.querySelector("#puntos").value = valueObject.puntos;

}

cargarInfo(<?= json_encode($this->solicitudData[0]) ?>);

</script>