<div class="modal fade" id="modalSolicitudes" tabindex="-1" aria-labelledby="modalSolicitudes" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Rechazar solicitud</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="closeModalAdm()">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST">
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Motivo del rechazo de la solicitud</label>
                        <textarea class="form-control" name="mensaje" rows="3"></textarea>
                        <input type='hidden' name='action' value='rechazar' />
                        <input type='hidden' name='id_usuario' value="<?= $this->solicitudData[0]["id_usuario"]; ?>" />
                    </div>

                    <div class="mt-3">
                        <input type="submit" class="btn btn-primary" value="Enviar" /> 
                    </div>
                </form>

            </div>
        
        </div>
    </div>
</div>


<div class="row">

    <div class="">

        <div class="row">
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-1 shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-principal text-uppercase mb-1">
                                    Puntos Solicitud</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800" id="label_pts"> 0 </div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="card flex-fill">

                <div class="card-header">
                    <h5 class="card-title mb-0"> Premios, menciones honoríficas y reconocimientos a nivel profesional: </h5>
                </div>

                <div class="card-body">

                    <form class="user needs-validation" method="POST" enctype="multipart/form-data" novalidate>
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <label class="form-label" for="institucion">Institución otorgante</label>
                                <input type="text" class="form-control form-control-user" id="institution" name="institucion" value="<?= $this->solicitudData[0]["institucion"]; ?>"
                                    placeholder="Institución otorgante" required disabled>
                                <div class="invalid-feedback">
                                    Por favor escriba el nombre de la institución
                                </div>
                                <!-- <div class="valid-feedback">
                                    Looks good!
                                </div> -->
                            </div>
                            <div class="col-sm-6">
                                <label for="fecha_obtencion">Fecha de obtención del reconocimiento</label>
                                <input type="date" class="form-control form-control-user" id="fecha_obtenida" name="fecha_obtenida" value="<?= $this->solicitudData[0]["fecha_obtenida"]; ?>"
                                    placeholder="Fecha de obtención del reconocimiento" required disabled>
                                <div class="invalid-feedback">
                                    Por favor escriba el año de obtención
                                </div>
                            </div>
                        </div>
                        

                        <!-- <div class="form-group">
                            <input type="text" class="form-control form-control-user" id="exampleLastName"
                            placeholder="Ingrese su número de registro docente">

                        </div> -->

                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <!-- <input type="password" class="form-control form-control-user"
                                    id="exampleInputPassword" placeholder="Tipo de reconocimiento"> -->
                                <label for="">Tipo de reconocimiento</label>
                                <select class="form-select form-control" aria-label="Default select example" name="reconocimiento" id="reconocimiento" onchange="validatePremios(this)" disabled required>
                                <option selected disabled value="">Escoja el tipo de reconocimiento</option>
                                    <option value="5.2">Reconocimientos y agradecimientos</option>
                                    <option value="5.1">Premios y/o menciones honoríficas</option>
                                </select>

                                <div class="invalid-feedback">
                                    Por favor selecciona el tipo de reconocimiento
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <label for="">Constancia del premio</label>
                                <div>
                                    <a class="btn btn-primary" href="<?= $this->url("meritosHome/meritos", ["action" => "displayfile" , "val1"=> $this->solicitudData[0]['url_file']]) ?>" target="_blank">
                                        Constancia
                                    </a>
                                </div>
                        
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <input type="hidden" class="form-control" value="1"
                                    id="id_estado" name="id_estado" required>
                            </div>

                            <div class="col-sm-6">
                                <input type="hidden" class="form-control" value="<?= $this->solicitudData[0]["id_usuario"]; ?>"
                                    id="id_usuario" name="id_usuario">
                            </div>

                            <div class="col-sm-6">
                                <input type="hidden" class="form-control" value="0" id="puntos" name="puntos">
                            </div>

                            <input type='hidden' name='action' value='aceptar' />

                        </div>

                        <h6 id="nota"></h6>

                        <div class="container">
                            <div class="row">
                                <div class="col-sm">
                                    <div class="mt-3">
                                        <input type="submit" class="btn btn-primary" value="Aceptar" /> 
                                    </div>
                                </div>
                                <div class="col-sm">
                                    <div class="mt-3">
                                        <a class="btn btn-danger" onclick="openModalAdm();">
                                            Rechazar
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </form>



                </div>
        
            </div>

    </div>

</div>


<script>


function cargarInfo(data) {
    console.log(data);
    const value = data.reconocimiento;
    document.getElementById("reconocimiento").value = value

    if (value == "5.1") {
        document.querySelector("#label_pts").innerHTML = "2";
        document.querySelector("#puntos").value = 2;
    } else if (value == "5.2") {
        document.querySelector("#label_pts").innerHTML = "1";
        document.querySelector("#puntos").value = 1;
    }
    

}

cargarInfo(<?= json_encode($this->solicitudData[0]) ?>);

</script>