<div class="row">

    <div class="">
        
        <div class="card flex-fill">

            <div class="card-header">
                <h5 class="card-title mb-0"> Solicitud de Capacitación profesional: Relacionada con la docencia </h5>
            </div>

            <div class="card-body">

                <form class="user">
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label class="form-label" for="institucion">Institución otorgante</label>
                            <input type="text" class="form-control form-control-user" id="institution"
                                placeholder="Institución otorgante">
                        </div>
                        <div class="col-sm-6">
                            <label for="">Nivel de titulo obtenido</label>
                            <select class="form-select form-control" aria-label="Default select example">
                            <option selected>Seleccione el nivel del titulo obtenido</option>
                                <option value="1">Doctorado</option>
                                <option value="2">Maestria</option>
                                <option value="2">Licenciatura</option>
                                <option value="2">Nivel intermedio</option>
                            </select>
                        </div>
                    </div>
                    

                    
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label for="">Seleccione la categoria</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="radio_nivel" id="flexRadioDefault1">
                                <label class="form-check-label" for="flexRadioDefault1">
                                    Graduado
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="radio_nivel" id="flexRadioDefault2" checked>
                                <label class="form-check-label" for="flexRadioDefault2">
                                    Cierre de pensum
                                </label>
                            </div>

                        </div>

                        <div class="col-sm-6">
                            <label for="fecha_obtencion">Año de graduación o cierre de pensum</label>
                            <input type="number" class="form-control form-control-user" id="fecha_obtencion"
                                placeholder="Escriba el año de obtención">

                        </div>

                    </div>

                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label for="">Constancia del titulo obtenido</label>
                            <input type="file" class="form-control"
                                id="archivo">
                        </div>
                        <div class="col-sm-6">
                            
                        </div>
                    </div>
                    

                    <div class="container">
                        <div class="row">
                            <div class="col-sm">
                                <a class="btn btn-success btn-user btn-block">
                                    Aceptar
                                </a>
                            </div>
                            <div class="col-sm">
                                <a class="btn btn-danger btn-user btn-block">
                                    Rechazar
                                </a>
                            </div>
                        </div>
                    </div>
                    
                </form>



            </div>
    
        </div>

    </div>

</div>