<div class="row">
    <div class="">
        <!-- <h1 class="h3 mb-2 text-gray-800"></h1> -->
        <div class="card flex-fill">
            <!-- <div class="card-header">
                <h5 class="card-title mb-0"> Configuración de tiempo de recepción de méritos curriculares </h5>
            </div> -->

            <div class="card-header">
                <h5 class="card-title mb-0"> Configuración general </h5>
            </div>
            <div class="card-body">

                <form class="user needs-validation" method="POST" enctype="multipart/form-data" novalidate>
                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label class="form-label" for="startDate">Fecha apertura</label>
                            <input type="date" class="form-control form-control-user" id="startDate" name="startDate" value="<?= $this->settings[0]["startDate"]; ?>" onchange="setMin();">
                        </div>
                        <div class="col-sm-6">
                            <label class="form-label" for="endDate">Fecha cierre</label>
                            <input type="date" class="form-control form-control-user" id="endDate" name="endDate" value="<?= $this->settings[0]["endDate"]; ?>" onchange="setMax();">
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <label class="form-label" for="startDate">Hora apertura</label>
                            <input type="time" class="form-control form-control-user" id="startTime" name="startTime" value="<?= $this->settings[0]["startTime"]; ?>" >
                        </div>
                        <div class="col-sm-6">
                            <label class="form-label" for="endDate">Hora cierre</label>
                            <input type="time" class="form-control form-control-user" id="endTime" name="endTime" value="<?= $this->settings[0]["endTime"]; ?>" >
                        </div>
                    </div>
                    <div class="form-group row" style="display:none;" id="group-nota">
                        <div class="">
                            <label class="form-label" for="nota">Nota:</label>
                            <textarea  class="form-control" name="nota" id="nota" rows="3" maxLength=150></textarea>
                        </div>
                    </div>
                    

                    <!-- <a class="btn btn-primary btn-user btn-block">
                        Guardar Configuración
                    </a> -->
                    
                    <div class="mt-3">
                        <div class="btn btn-dark" id="btn-nota" onclick="activateTxt();">
                            Agregar nota
                        </div>
                    </div>

                    <div class="mt-3">
                        <input type="submit" class="btn btn-primary btn-user" value="Guardar configuración" /> 
                    </div>
                    
                </form>



            </div>

        </div>

    </div>
        
</div>