

<div class="container-fluid">

    <!-- Content Row -->
    <div class="row">

        <!-- Premios -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-1 shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">

                            <div class="text-xs font-weight-bold text-principal text-uppercase mb-1">Puntos premios, menciones honorificas y reconocimientos
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800" id="valuePremios">0/2</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-1" role="progressbar" id="porcentajePremios"
                                            style="width: 100%" aria-valuenow="50" aria-valuemin="0"
                                            aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fa-solid fa-award fa-2x text-gray-300"></i>
                            <!-- <i class="fas fa-calendar fa-2x text-gray-300"></i> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Investigaciones/publicaciones -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-2 shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-principal text-uppercase mb-1">Puntos Investigaciones/publicaciones
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800" id="valueInvestigaciones">0/6</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-2" role="progressbar" id="porcentajeInvestigaciones"
                                            style="width: 100%" aria-valuenow="50" aria-valuemin="0"
                                            aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fa-solid fa-book fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Formación académica -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-3 shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-principal text-uppercase mb-1">Puntos formación académica
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800" id="valueFormacionAcademica">0/10</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-3" role="progressbar" id="porcentajeFormacionAcademica"
                                            style="width: 100%" aria-valuenow="50" aria-valuemin="0"
                                            aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fa-solid fa-school fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->

    <div class="row">
        <!-- Cargos desempeñados -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-4 shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-principal text-uppercase mb-1">Puntos de Cargos desempeñados
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800" id="valueCargos">0/4</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-4" role="progressbar" id="porcentajeCargos"
                                            style="width: 100%" aria-valuenow="50" aria-valuemin="0"
                                            aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <!-- <i class="fas fa-comments fa-2x text-gray-300"></i> -->
                            <i class="fa-solid fa-person-chalkboard fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-5 shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-principal text-uppercase mb-1">Puntos Capacitación Profesional
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800" id="valueCapacitacion">0/4</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-5" role="progressbar" id="porcentajeCapacitacion"
                                            style="width: 100%" aria-valuenow="50" aria-valuemin="0"
                                            aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Puntos totales -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-6 shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">

                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-principal text-uppercase mb-1">Puntos totales
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800" id="total"><?= $miPuntaje ?> /30</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-6" role="progressbar" id="porcentajeTotal"
                                            style="width: 100%" aria-valuenow="50" aria-valuemin="0"
                                            aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Mis solicitudes</h1>

    <!-- Modal para mostrar el archivo -->
    <div class="modal fade" id="modalPdf" tabindex="-1" aria-labelledby="modalPdf" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Constancia de mérito académico</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="closeModal()">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <iframe id="iframePDF" frameborder="0" scrolling="no" width="100%" height="500px"></iframe>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="closeModal()">Cerrar</button>

                    </div>
                </div>
            </div>
    </div>


    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Solicitudes de Meritos curriculares</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
            <table class="table table-bordered dtable" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Fecha de solicitud</th>
                            <th>Tipo de solicitud</th>
                            <th>Puntos del mérito</th>
                            <th>Constancia</th>
                            <th>Estado solicitud</th>
                            <th>Mensaje</th>
                            <th>Editar solicitud</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->premios as $tmp): ?>
                            <tr>
                                <td><?= $tmp["updated_at"] ?></td>
                                <td>Premios, menciones honoríficas y reconocimientos a nivel profesional</td>
                                <td><?= $tmp["puntos"] ?></td>
                                <td> 
                                    <a class="btn btn-primary" href="<?= $this->url("meritosHome/meritos", ["action" => "displayfile" , "val1"=> $tmp['url_file']]) ?>" target="_blank">
                                        Constancia
                                    </a>
                                </td>
                                <td> <span class="badge badge-<?= $tmp["color"] ?>" > <?= $tmp["nombre_estado"] ?> </span></td>
                                <td><?= $tmp["mensaje"] ?></td>
                                <td>
                                    <?php if ( $tmp["nombre_estado"] == 'Ingresada'): ?>
                                        <a class="btn btn-primary btn-sm1" href="<?= $this->url("meritosHome/meritos", ["action" => "premios" , "val1"=> "edit", "val2"=>$tmp["id_premio"]]) ?>">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        <?php foreach ($this->cargos as $tmp): ?>
                            <tr>
                                <td><?= $tmp["updated_at"] ?></td>
                                <td>Cargos desempeñados</td>
                                <td><?= $tmp["puntos"] ?></td>
                                <td> 
                                    <a class="btn btn-primary" href="<?= $this->url("meritosHome/meritos", ["action" => "displayfile" , "val1"=> $tmp['url_constancia']]) ?>" target="_blank">
                                        Constancia
                                    </a>
                                </td>
                                <td> <span class="badge badge-<?= $tmp["color"] ?>" > <?= $tmp["nombre_estado"] ?> </span></td>
                                <td><?= $tmp["mensaje"] ?></td>
                                <td>
                                    <?php if ( $tmp["nombre_estado"] == 'Ingresada'): ?>
                                        <a class="btn btn-primary btn-sm1" href="<?= $this->url("meritosHome/meritos", ["action" => "cargos" , "val1"=> "edit", "val2"=>$tmp["id_cargo"]]) ?>">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        <?php foreach ($this->formacionAcademica as $tmp): ?>
                            <tr>
                                <td><?= $tmp["updated_at"] ?></td>
                                <td>Formación profesional</td>
                                <td><?= $tmp["puntos"] ?></td>
                                <td> 
                                    <a class="btn btn-primary" href="<?= $this->url("meritosHome/meritos", ["action" => "displayfile" , "val1"=> $tmp['url_constancia']]) ?>" target="_blank">
                                        Constancia
                                    </a>  
                                </td>
                                <td> <span class="badge badge-<?= $tmp["color"] ?>" > <?= $tmp["nombre_estado"] ?> </span></td>
                                <td><?= $tmp["mensaje"] ?></td>
                                <td>
                                    
                                    <?php if ( $tmp["nombre_estado"] == 'Ingresada'): ?>
                                        <a class="btn btn-primary btn-sm1" href="<?= $this->url("meritosHome/meritos", ["action" => "formacionAcademica" , "val1"=> "edit", "val2"=>$tmp["id_formacion_academica"]]) ?>">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        <?php foreach ($this->capacitacionProfesional as $tmp): ?>
                            <tr>
                                <td><?= $tmp["updated_at"] ?></td>
                                <td>Capacitación profesional: Relacionada con la docencia</td>
                                <td><?= $tmp["puntos"] ?></td>
                                <td> 
                                    <!-- <button class="btn btn-primary" onclick="openModelPDF('<?= $tmp['url_constancia'] ?>', '<?= $_SERVER['HTTP_HOST'] ?>')">
                                        Constancia
                                    </button> -->
                                    <a class="btn btn-primary" href="<?= $this->url("meritosHome/meritos", ["action" => "displayfile" , "val1"=> $tmp['url_constancia']]) ?>" target="_blank">
                                        Constancia
                                    </a>
                                </td>
                                <td> <span class="badge badge-<?= $tmp["color"] ?>" > <?= $tmp["nombre_estado"] ?> </span></td>
                                <td><?= $tmp["mensaje"] ?></td>
                                <td>
                                    <?php if ( $tmp["nombre_estado"] == 'Ingresada'): ?>
                                        <a class="btn btn-primary btn-sm1" href="<?= $this->url("meritosHome/meritos", ["action" => "capacitacionProfesional" , "val1"=> "edit", "val2"=>$tmp["id_capacitacion"]]) ?>">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        <?php foreach ($this->investigaciones as $tmp): ?>
                            <tr>
                                <td><?= $tmp["updated_at"] ?></td>
                                <td>Investigaciones y/o publicaciones realizadas</td>
                                <td><?= $tmp["puntos"] ?></td>
                                <td> 
                                    <a class="btn btn-primary" href="<?= $this->url("meritosHome/meritos", ["action" => "displayfile" , "val1"=> $tmp['url_constancia']]) ?>" target="_blank">
                                        Constancia
                                    </a>
                                </td>
                                <td> <span class="badge badge-<?= $tmp["color"] ?>" > <?= $tmp["nombre_estado"] ?> </span></td>
                                <td><?= $tmp["mensaje"] ?></td>
                                <td>
                                    <?php if ( $tmp["nombre_estado"] == 'Ingresada'): ?>
                                        <a class="btn btn-primary btn-sm1" href="<?= $this->url("meritosHome/meritos", ["action" => "investigaciones" , "val1"=> "edit", "val2"=>$tmp["id_investigacion"]]) ?>">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

<script>
    function cargarInfo(puntos, puntosTotales){
        console.log(puntos);
        let premios = 2;
        let investigaciones = 6;
        let capacitacion = 8;
        let formacion = 10;
        let cargos = 4;
        const total = 30;

        let porcentajePremios = ((Number(puntos.premios))/premios)*100;
        let porcentajeInvestigaciones = ((Number(puntos.investigaciones))/investigaciones)*100;
        let porcentajeFormacionAcademica = ((Number(puntos.formacion_academica))/formacion)*100;
        let porcentajeCargos = ((Number(puntos.cargos))/cargos)*100;
        let porcentajeCapacitacion = ((Number(puntos.capacitacion_profesional))/capacitacion)*100;
        let porcentajeTotal = ((Number(puntosTotales))/total)*100;

        document.querySelector("#valuePremios").innerHTML = `${puntos.premios}/${premios}` ;
        document.getElementById('porcentajePremios').style.width = `${porcentajePremios}%`;

        document.querySelector("#valueInvestigaciones").innerHTML = `${puntos.investigaciones}/${investigaciones}` ;
        document.getElementById('porcentajeInvestigaciones').style.width = `${porcentajeInvestigaciones}%`;

        document.querySelector("#valueFormacionAcademica").innerHTML = `${puntos.formacion_academica}/${formacion}` ;
        document.getElementById('porcentajeFormacionAcademica').style.width = `${porcentajeFormacionAcademica}%`;

        document.querySelector("#valueCargos").innerHTML = `${puntos.cargos}/${cargos}` ;
        document.getElementById('porcentajeCargos').style.width = `${porcentajeCargos}%`;

        document.querySelector("#valueCapacitacion").innerHTML = `${puntos.capacitacion_profesional}/${capacitacion}` ;
        document.getElementById('porcentajeCapacitacion').style.width = `${porcentajeCapacitacion}%`;
        
        document.getElementById('porcentajeTotal').style.width = `${porcentajeTotal}%`;


    }

    cargarInfo(<?= json_encode($this->puntos[0]) ?> , <?= $miPuntaje ?> );
</script> 