
  <nav class="navbar navbar-expand navbar-light bg-white topbar static-top shadow">
      <!-- <h5 class="my-0 mr-md-auto font-weight-normal">COMEVAL</h5> -->
      <img src="<?= $this->basePath('img/icons/logoceda.png') ?>" alt="" width="100px;">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>
        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="btn btn-primary btn-user btn-block" href="<?= $this->url("administracionHome/administracion", ["action" => "homepage"]) ?>">
                    <span>Iniciar sesión</span></a>
            </li>
        </ul>

    </nav>


    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Comisión de Evaluación Docente FARUSAC</h1>
          <!-- <p class="lead text-muted">Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe porro dolores velit excepturi dolorem earum maiores, debitis inventore sunt recusandae, illo magni ab iste repudiandae, consectetur nostrum est enim hic?</p> -->
  
        </div>
      </section>


      <div class="container">
      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Misión</h4>
          </div>
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <p>
                Evaluar ecuánime, ética y pertinentemente el desempeño laboral de los docentes,
                a través de un sistema conveniente.
              </p>
            </ul>
            <!-- <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button> -->
          </div>
        </div>
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Visión</h4>
          </div>
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <p>
                Ser un ente orientar y evaluador del desempeño y formación de los docentes de la
                facultad de Arquitectura. Gestiona el proceso de evaluación ante las instancias
                respectivas y comunica resultados mediante la utilización de las tecnologías clara
                y veras de forma eficiente.
              </p>
            </ul>
          </div>
        </div>
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Contactanos</h4>
          </div>
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <p><i class="fas fa-envelope"></i> evaluacion.docente@farusac.edu.gt</p>
              <a href="./Manual_de_usuario_Docente-CEDA.pdf">Manual de usuario</>
            </ul>
 
          </div>
        </div>
      </div>


    </div>

    </main>
