<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!-- <div class="row mt-5 mb-5">
    <div class="col-xl-4 offset-xl-4 offset-0 col-12 mt-4">
        <?php if (!$this->resultado): ?>
            <form class="form" method="POST" >
                <div class="col-12">
                    <input type="email" name="email" class="form-control" placeholder="Correo registrado en la plataforma" required />
                </div>
                <div class="col-12">
                    <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Recuperar</button>
                </div>
            </form>
        <?php else: ?>
        <a class="btn btn-lg btn-success btn-block mt-2" href="<?= $this->url('home') ?>">Regresar</a>
        <?php endif; ?>
    </div>
</div> -->

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- <h5 class="my-0 mr-md-auto font-weight-normal">COMEVAL</h5> -->
    <img src="<?= $this->basePath('img/icons/logoceda.png') ?>" alt="" width="100px;">


    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="<?= $this->url('welcome') ?>">
                <i class="fas fa-home"></i>
                <!-- <span>Inicio</span> -->
            </a>
        </li>
        <!-- <div class="topbar-divider d-none d-sm-block"></div> -->
    </ul>

</nav>

<div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">¿Olvidaste tu contraseña?</h1>
                                        <p class="mb-4">Lo entendemos, suele pasar. ¡Simplemente ingrese su dirección de correo electrónico a continuación y le enviaremos una contraseña temporal para que pueda ingresar nuevamente!</p>
                                    </div>
                                    <form class="user" method="POST">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="email" name="email" aria-describedby="email"
                                                placeholder="Ingresa un correo registrado en la plataforma...">
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Recuperar contraseña
                                        </button>
                                    </form>
                                    <hr>
                                    <!-- <div class="text-center">
                                        <a class="small" href="register.html">¡Crea una cuenta!</a>
                                    </div> -->
                                    <div class="text-center">
                                        <a class="small" href="<?= $this->url('home') ?>">¿Ya tienes una cuenta? ¡Ingresa!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>


