<div class="row">
    <!-- <div class="col-12">
        <center><h2 class="text-danger">Acceso denegado</h2></center>
    </div> -->
    <div class="container-fluid">

        <!-- 404 Error Text -->
        <div class="text-center">
            <div class="error mx-auto" data-text="403">403</div>
            <p class="lead text-gray-800 mb-5">El periodo se encuentra inactivo...</p>
            <p class="text-gray-500 mb-0">Parece que encontraste una falla en la matriz...</p>
            <a href="<?= $this->url('home') ?>">&larr; Volver al panel</a>
        </div>

    </div>


</div>



