<div class="row">
    <div class="col-12">
        <center><h2>Gestión de permisos</h2></center>
    </div>

    <?php if ($this->acceso[0] == 1): ?>
        <form method="POST">
        <?php endif; ?>
        <?php foreach ($this->dataPermisos as $modulo => $permisos): ?>

            <div class="col-12">
                <center><h3>Módulo: <?= $modulo ?></h3></center>
            </div>

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Plataforma</th>
                        <th>Menú</th>
                        <th>Descripción</th>
                        <th>Permisos</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($permisos as $tmp) {

                        $menuSeparado = explode("|", $tmp["menu"]);
                        ?>
                        <tr>
                            <td><?= $menuSeparado[0] ?></td>
                            <td><?= $menuSeparado[1] ?></td>
                            <td><?= $tmp["nombre"] ?></td>
                            <td>
                                <?php
                                $arrayAcciones = json_decode($tmp["acciones"], true);
                                $contador = 0;
                                foreach ($arrayAcciones as $o) {
                                    ?>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="check<?=  $contador ?>[<?= $tmp["permiso"] ?>]" name="check<?=  $contador ?>[<?= $tmp["permiso"] ?>]"  
                                               <?= (isset($this->data[$tmp["permiso"]]) && ($contador == 0 || ($contador > 0 && $this->data[$tmp["permiso"]][$contador - 1] == 1))) ? "checked" : "" ?> >
                                        <label class="form-check-label" for="check<?=  $contador ?>[<?= $tmp["permiso"] ?>]">
                                            <?= $o ?>
                                        </label>
                                    </div>
                                    <?php
                                    $contador++;
                                }
                                ?>
                                
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>

        <?php endforeach; ?>
        <?php if ($this->acceso[0] == 1): ?>
            <div class="form-group">
                <button class="btn-success btn" type="submit">Guardar</button>
            </div>
        </form>
    <?php endif; ?>

</div>

